### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by lizOnly** [bizerfr/BPNet#1]
Hi,

I am reading your publication; It is quite an excellent work!
Could you please release the source code?

Thank you!

**Comment by bizerfr** [comment]
Hello.
Thank you for reading our publication. We are cleaning the code and preparing the camera-ready version. Please be patient.

**Comment by bizerfr** [comment]
> Hi,
> 
> I am reading your publication; It is quite an excellent work! Could you please release the source code?
> 
> Thank you!

Hello,

The code is released.

Thanks!
