### ISSUE TITLE
Inference and labels

### ISSUE THREAD

**Issue by lutfia95** [bizerfr/BPNet#2]
Dear Authors, 

thank you very much for providing this amazing model! can you please give me an example, how can I run the pre-trained on model on mesh file? Regarding labeling, does the inference mesh become labels? 

Best,
Ahmad

**Comment by lutfia95** [comment]
Hey @bizerfr , 

I could successfully run the inference! but I still not sure if I understood the output correctly! The output was point cloud sampled from mesh. The input point cloud contains the coordinates x,y and z. The output was almost the same input data without any information about segmentation. Is there any specific parameter for the input data? so that I get segmented parts? 

Best,
Ahmad

**Comment by bizerfr** [comment]
Hi Ahmad,

    Generally, the input is point clouds sampled from mesh, especially from CAD models. And if normals are provided, it can gain better results.  The format is:
```
x y z nx ny nz 
....
```

The output should be obj files with each color indicating a patch. I only save the obj file using the function ''write_colored_points_with_labels_obj". The key is:

```
s = 'v {} {} {} {} {} {}  #{}\n'.format(mesh_v[i, 0], mesh_v[i, 1], mesh_v[i, 2], 
                                               colors[i, 0], colors[i, 1], colors[i, 2],
                                               ids[i])
```
where the comment `#" indicates the patch label.

I suggest using meshlab for visualization.

Best regards,

**Comment by bizerfr** [comment]
Hi Ahmad,

Generally, the input is point clouds sampled from mesh, especially from CAD models. And if normals are provided, it can gain better results.  The format is:
```
x y z nx ny nz 
....

```
The output should be obj files with each color indicating a patch. I only save the obj file using the function ''write_colored_points_with_labels_obj". The key is:

```
s = 'v {} {} {} {} {} {}  #{}\n'.format(mesh_v[i, 0], mesh_v[i, 1], mesh_v[i, 2], 
                                               colors[i, 0], colors[i, 1], colors[i, 2],
                                               ids[i])
```
where the comment `#" indicates the patch label.

I suggest using meshlab for visualization.

Best regards,

**Comment by lutfia95** [comment]
Thanks ;)

**Comment by Tomoki-0526** [comment]
> Hi Ahmad,
> 
> Generally, the input is point clouds sampled from mesh, especially from CAD models. And if normals are provided, it can gain better results. The format is:
> 
> ```
> x y z nx ny nz 
> ....
> ```
> 
> The output should be obj files with each color indicating a patch. I only save the obj file using the function ''write_colored_points_with_labels_obj". The key is:
> 
> ```
> s = 'v {} {} {} {} {} {}  #{}\n'.format(mesh_v[i, 0], mesh_v[i, 1], mesh_v[i, 2], 
>                                                colors[i, 0], colors[i, 1], colors[i, 2],
>                                                ids[i])
> ```
> 
> where the comment `#" indicates the patch label.
> 
> I suggest using meshlab for visualization.
> 
> Best regards,

Hello bizerfr, I'm using your work to inference a point cloud from BIM. According to your reply, the "ids" in the output is unique for different patches. But I find two patches share the same id and color, is it right or did I make any mistake?
![屏幕截图 2024-08-05 124744](https://github.com/user-attachments/assets/328daf12-81bd-4efb-aedc-2361f23dc51e)
![屏幕截图 2024-08-05 124854](https://github.com/user-attachments/assets/a6aeaf9f-32f9-45a8-b5d8-db3a8f8b1330)
![屏幕截图 2024-08-05 125126](https://github.com/user-attachments/assets/7094a93d-fcbf-4909-8996-8ac1428f9858)

**Comment by Tomoki-0526** [comment]
> Hi Ahmad,
> 
> Generally, the input is point clouds sampled from mesh, especially from CAD models. And if normals are provided, it can gain better results. The format is:
> 
> ```
> x y z nx ny nz 
> ....
> ```
> 
> The output should be obj files with each color indicating a patch. I only save the obj file using the function ''write_colored_points_with_labels_obj". The key is:
> 
> ```
> s = 'v {} {} {} {} {} {}  #{}\n'.format(mesh_v[i, 0], mesh_v[i, 1], mesh_v[i, 2], 
>                                                colors[i, 0], colors[i, 1], colors[i, 2],
>                                                ids[i])
> ```
> 
> where the comment `#" indicates the patch label.
> 
> I suggest using meshlab for visualization.
> 
> Best regards,

Hello @bizerfr , I'm using your work to inference a point cloud from BIM. According to your reply, the "ids" in the output is unique for different patches. But I find two patches share the same id and color, is it right or did I make any mistake?
![屏幕截图 2024-08-05 124744](https://github.com/user-attachments/assets/33b700b3-5005-4e5d-ae39-20b64783e6f1)
![屏幕截图 2024-08-05 124854](https://github.com/user-attachments/assets/88eeaeb3-7fb7-4a76-b1af-44a8b4a083f9)
![屏幕截图 2024-08-05 125126](https://github.com/user-attachments/assets/8c5eb504-2d77-40e0-b49f-752f31925607)

**Comment by bizerfr** [comment]
> > Hi Ahmad,
> > Generally, the input is point clouds sampled from mesh, especially from CAD models. And if normals are provided, it can gain better results. The format is:
> > ```
> > x y z nx ny nz 
> > ....
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The output should be obj files with each color indicating a patch. I only save the obj file using the function ''write_colored_points_with_labels_obj". The key is:
> > ```
> > s = 'v {} {} {} {} {} {}  #{}\n'.format(mesh_v[i, 0], mesh_v[i, 1], mesh_v[i, 2], 
> >                                                colors[i, 0], colors[i, 1], colors[i, 2],
> >                                                ids[i])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > where the comment `#" indicates the patch label.
> > I suggest using meshlab for visualization.
> > Best regards,
> 
> Hello @bizerfr , I'm using your work to inference a point cloud from BIM. According to your reply, the "ids" in the output is unique for different patches. But I find two patches share the same id and color, is it right or did I make any mistake? ![屏幕截图 2024-08-05 124744](https://private-user-images.githubusercontent.com/73088234/354972997-33b700b3-5005-4e5d-ae39-20b64783e6f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDQ3NDcsIm5iZiI6MTcyNTQ0NDQ0NywicGF0aCI6Ii83MzA4ODIzNC8zNTQ5NzI5OTctMzNiNzAwYjMtNTAwNS00ZTVkLWFlMzktMjBiNjQ3ODNlNmYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDEwMDcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2ZjVmM2FiNTJmYmJiMzNiZTg2MGQ0MTE2ZGU1MTUzMzBjNjU0NjMxMWYyZjJhZWY0MWNmYWM3MzMxZmNjM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UrX1-9NCrsDaUColrg-0X2n18Ol8hI33koHIZoUM-vM) ![屏幕截图 2024-08-05 124854](https://private-user-images.githubusercontent.com/73088234/354973001-88eeaeb3-7fb7-4a76-b1af-44a8b4a083f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDQ3NDcsIm5iZiI6MTcyNTQ0NDQ0NywicGF0aCI6Ii83MzA4ODIzNC8zNTQ5NzMwMDEtODhlZWFlYjMtN2ZiNy00YTc2LWIxYWYtNDRhOGI0YTA4M2Y5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDEwMDcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3NTY2Y2U5NjgwOTRiZmQ0ODZkMWE4ZWNjZTczYWFmODU4NzVjMTgyZDVhYzMyMGVlYWYwZDFiMDU2YzA3YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MKo_60_aux5bJK2OLVQBaIpr3kjiDK5oO5aoNcAAvlc) ![屏幕截图 2024-08-05 125126](https://private-user-images.githubusercontent.com/73088234/354973002-8c5eb504-2d77-40e0-b49f-752f31925607.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDQ3NDcsIm5iZiI6MTcyNTQ0NDQ0NywicGF0aCI6Ii83MzA4ODIzNC8zNTQ5NzMwMDItOGM1ZWI1MDQtMmQ3Ny00MGUwLWI0OWYtNzUyZjMxOTI1NjA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDEwMDcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhMTNkZTc1Yzk5MDRiNjUxNWVhMDQ0OGFiZGY4YjdjZmQyMmU2MzEwOTI2NTIzZDlhMzhmNmIyZmM4YzNkMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HEp5oUAYWAdx1bd_1JcSlekKs5ZJBCXaf2IteGZPhYM)

Hi, I'm not sure if the algorithm suits your input. I didn't try the point cloud from BIM.
