### ISSUE TITLE
non normal pretrained model

### ISSUE THREAD

**Issue by lakiet1609** [bizerfr/BPNet#5]
It seems like your pretrained model trained with data having normals. So while I am inferencing the with not normal input, there will be a mismatch between my input and your pretrained model ! So is there any chance to fix it without training the new model or whether you have the non-normal pretrained model ?

**Comment by bizerfr** [comment]
Yes, the pre-trained model here needs both point coordinates and normals.
If you want to use the pre-trained model, the simplest way is to append [0.0, 0.0, 0.0] for each coordinate.
Or, you can change "--input_normal" to "0" in the "option.py" to retrain a model without using normals.
